Repository qbcore-framework/qb-core, pull requests merged in 2022-12, with the labels that each got.

#898 [FIX] Add baseevents back
  client/events.lua
  server/events.lua
Labels: bug

#899 🎨 Refactor: Refactors jobs conditional statement
  shared/jobs.lua
Labels: refactor

#897 [SECURITY] Remove insecure event
  server/events.lua
Labels: security

#893 [FIX] shared/vehicles.lua car names & other issues
  shared/vehicles.lua
Labels: bug

#901 [FIX] more shared/vehicles.lua car names & brands
  shared/vehicles.lua
Labels: bug
