Repository qbcore-framework/qb-core, pull requests merged in 2022-03, with the labels that each got.

#536 [dev branch] Some additions
  client/events.lua
  client/functions.lua
  client/loops.lua
  config.lua
  fxmanifest.lua
  locale/es.lua
  server/commands.lua
  server/debug.lua
  server/events.lua
  server/exports.lua
  server/functions.lua
  server/main.lua
  server/player.lua
  shared/locale.lua
  shared/main.lua
Labels: enhancement, help wanted, Needs Testing/Reviews

#597 [Fix] Livery Mod Saving
  client/functions.lua
Labels: bug

#594 WIP Permissions System
  config.lua
  server/commands.lua
  server/events.lua
  server/functions.lua
  server/main.lua
  server/player.lua
Labels: enhancement, Needs Testing/Reviews
